/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/7n1t8li3j4i
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function projects() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
        <div className="group relative overflow-hidden rounded-lg shadow-lg transition-all duration-300 hover:-translate-y-2 hover:shadow-xl">
          <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
            <span className="sr-only">View Project</span>
          </Link>
          <img
            src="/placeholder.svg"
            width={600}
            height={400}
            alt="Project 1"
            className="h-64 w-full object-cover transition-all duration-300 group-hover:scale-105"
            style={{ aspectRatio: "600/400", objectFit: "cover" }}
          />
          <div className="bg-background p-4">
            <h3 className="text-xl font-bold">Project 1</h3>
            <p className="text-muted-foreground">A brief description of the first project.</p>
          </div>
        </div>
        <div className="group relative overflow-hidden rounded-lg shadow-lg transition-all duration-300 hover:-translate-y-2 hover:shadow-xl">
          <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
            <span className="sr-only">View Project</span>
          </Link>
          <img
            src="/placeholder.svg"
            width={600}
            height={400}
            alt="Project 2"
            className="h-64 w-full object-cover transition-all duration-300 group-hover:scale-105"
            style={{ aspectRatio: "600/400", objectFit: "cover" }}
          />
          <div className="bg-background p-4">
            <h3 className="text-xl font-bold">Project 2</h3>
            <p className="text-muted-foreground">A brief description of the second project.</p>
          </div>
        </div>
        <div className="group relative overflow-hidden rounded-lg shadow-lg transition-all duration-300 hover:-translate-y-2 hover:shadow-xl">
          <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
            <span className="sr-only">View Project</span>
          </Link>
          <img
            src="/placeholder.svg"
            width={600}
            height={400}
            alt="Project 3"
            className="h-64 w-full object-cover transition-all duration-300 group-hover:scale-105"
            style={{ aspectRatio: "600/400", objectFit: "cover" }}
          />
          <div className="bg-background p-4">
            <h3 className="text-xl font-bold">Project 3</h3>
            <p className="text-muted-foreground">A brief description of the third project.</p>
          </div>
        </div>
      </div>
    </section>
  )
}
